name: Build and Deploy Angular App

on:
  push:
    branches:
      - release  # o il branch che usi

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'

    - name: Install Yarn
      run: corepack enable && corepack prepare yarn@stable --activate

    - name: Install dependencies
      run: yarn install

    - name: Build Angular app
      run: yarn build -- --configuration production

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        #github_token: ${{ secrets.GITHUB_TOKEN }}
        personal_token: ${{ secrets.GH_TOKEN }}
        publish_dir: ./dist  # <- metti qui il path corretto
